- package.json
> chore(deps): add missing dependency

- README.md
- env.js
- package.json
Adds a way to handle environment variables, which is like very necessary hah
> feat(env): add

- index.js
> fix log method

- .gitignore
- .travis.yml
- package.json
- test.js
- test/index.js
> add http handler tests

- index.js
makes it so `listen()` calls back when done booting
> call back on listen

- README.md
- index.js
- package.json
- test/index.js
creates a parse method for json + string as mentioned in #20
> create body parsers

- README.md
- index.js
- package.json
- test/index.js
Adds middleware, closes #26 :tada:
> Malcom in the middleware

- README.md
- index.js
- package.json
- test/index.js
yay, closes #39 - adds `json-schema` support
> Json schema

- README.md
- index.js
- package.json
- test/index.js
Improves our error handling by wrapping `boom`. Closes #30 :tada:
> Itsa feature not an error

- index.js
Hi!
I've tried to play with Merry, but I cannot change the `logLevel` from `'info'` to '`fatal'`, I guess because of this.
Cheers! :)
> Added logLevel option

- index.js
ref https://github.com/yoshuawuyts/merry/pull/57
> Bpillatsch master

- README.md
- index.js
- package.json
Adds a multipart parser. Closes #35 :tada:
> add multipart parser

- index.js
ayeee, chaining syntax :sparkles:
> return self on router

- README.md
Moving some docs stuff around; temporarily removed CORS in preparation of #64
> restructure docs

- example.js
- index.js
envobj should wrap opts.env when starting merry
> fix env obj func

- README.md
- index.js
- package.json
- test/context.js
- test/index.js
implements the `ctx.parse` method as per #92, and updates the docs a lil. Thanks!
> add ctx.parse method

- index.js
> lol oops log

- README.md
- index.js
- package.json
Upgrade to the latest server-router. Thanks!
> upgrade to server-router 5.2

- index.js
> set json header

- test/index.js
- Add a assertions for correct content-type when an object is sent as the response.
> test: Add checks for correct content-type.

- README.md
- example.js
- index.js
- test/index.js
adds an app.use functionality to handle application-wide req/res/ctx modifications.
> add app.use
